export const CITIES = [
  { city: 'Novosibirsk', country: 'Russia' },
  { city: 'Moscow', country: 'Russia' },
  { city: 'New York', country: 'USA' },
  { city: 'Los Angeles', country: 'USA' },
  { city: 'Beijing', country: 'China' },
  { city: 'Shanghai', country: 'China' },
  { city: 'Tokyo', country: 'Japan' },
  { city: 'Osaka', country: 'Japan' },
  { city: 'Hanoi', country: 'Vietnam' },
  { city: 'Ho Chi Minh City', country: 'Vietnam' },
  { city: 'Bangkok', country: 'Thailand' },
  { city: 'Chiang Mai', country: 'Thailand' },
  { city: 'Rome', country: 'Italy' },
  { city: 'Milan', country: 'Italy' },
  { city: 'Almaty', country: 'Kazakhstan' },
  { city: 'Astana', country: 'Kazakhstan' },
  { city: 'Minsk', country: 'Belarus' },
  { city: 'Brest', country: 'Belarus' },
  { city: 'Dubai', country: 'UAE' },
  { city: 'Abu Dhabi', country: 'UAE' },
]